apiVersion: v1
kind: Service
metadata:
  name: analytics-web
  namespace: analytics-gitops
  labels:
    app: analytics-web
spec:
  type: NodePort
  selector:
    app: analytics-web
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
